// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxbluzkvpfzkdibuaztp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4Ymx1emt2cGZ6a2RpYnVhenRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTQ0NjUsImV4cCI6MjA2OTQ3MDQ2NX0.NgeKhgmahpLlPuXJHwS4eWhIFRC8GYuxSPnBd-sIwTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});